#!/usr/bin/env python3
"""Benchmark tlsf-tools as a decomposition preprocessor for synthesis, against
standalone acacia-bonsai.

Two metrics, both rerunnable over the corpus and summarised into BENCHGRAPH.md:

  ROUTE SHAPE (whole corpus): how many residual clusters are solved in process,
  and what shape are the residual clusters that still need an external backend.

  SPEED: wall time of the wrapper pipeline (decompose + persistent OxiDD residual
  solving + external acacia-bonsai per remaining cluster + merge) vs a standalone
  acacia-bonsai baseline for the whole spec.  Solve STATUS is tracked too -- a
  fast failure is not a speedup, so speedups are only computed where both engines
  actually produced a controller.

Usage:
  scripts/benchgraph.py --corpus DIR --tlsfcompose PATH \
      [--solver PATH] [--out BENCHGRAPH.md] [--data data.tsv] \
      [--timeout 10] [--mem-gb 6] [--speed all|routed]
"""
import argparse
import csv
import itertools
import os
import re
import shutil
import signal
import statistics
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timezone

# Per-child memory cap, enforced via a systemd transient scope (cgroup) -- set
# from --mem-gb in main().  RLIMIT_AS cannot be used: OxiDD reserves large
# virtual pools (>6 GB) even for tiny games, causing spurious SIGABRT panics; and
# RLIMIT_RSS is advisory-only on Linux.  A `systemd-run --user --scope` cgroup
# with MemoryMax + MemorySwapMax=0 gives a *hard* RSS+swap cap whose breach kills
# only that child's cgroup (verified), never the whole box -- which an unenforced
# cap previously let the OS OOM killer do.
MEM_GB = 6
FORCE_NO_CGROUP = False
SENTINEL_START = "<!-- BENCHGRAPH:PREPROCESSOR START (generated by scripts/benchgraph.py) -->"
SENTINEL_END = "<!-- BENCHGRAPH:PREPROCESSOR END -->"
ROW_FIELDS = [
    "name",
    "preprocessor_only",
    "oxidd_clusters",
    "external_clusters",
    "residual_class",
    "preproc_st",
    "preproc_t",
    "acacia_st",
    "acacia_t",
    "full_nodes",
    "external_nodes",
    "full_bytes",
    "external_bytes",
    "max_outputs_any_cluster",
    "max_outputs_external",
]
INT_FIELDS = [
    "oxidd_clusters",
    "external_clusters",
    "full_nodes",
    "external_nodes",
    "full_bytes",
    "external_bytes",
    "max_outputs_any_cluster",
    "max_outputs_external",
]
FLOAT_FIELDS = ["preproc_t", "acacia_t"]


def systemd_run_usable():
    if shutil.which("systemd-run") is None:
        return False
    try:
        proc = subprocess.run(
            ["systemd-run", "--user", "--scope", "--quiet", "--collect",
             "--", "true"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return proc.returncode == 0


HAVE_SYSTEMD_RUN = systemd_run_usable()
SYSTEMD_SCOPE_COUNTER = itertools.count(1)


def _systemd_scope_name():
    return f"tlsfbench-{os.getpid()}-{next(SYSTEMD_SCOPE_COUNTER)}"


def _prepare_child_cmd(cmd):
    """Prepend a systemd transient-scope cgroup with a hard memory cap.  --quiet
    keeps the child's stderr clean (we parse it); --collect reaps the unit even
    on failure; MemorySwapMax=0 stops the child eating (zram) swap."""
    if FORCE_NO_CGROUP or not HAVE_SYSTEMD_RUN:
        return list(cmd), None
    unit = _systemd_scope_name()
    return ["systemd-run", "--user", "--scope", "--quiet", "--collect",
            "--unit", unit,
            "-p", f"MemoryMax={MEM_GB}G", "-p", "MemorySwapMax=0",
            "--"] + list(cmd), unit + ".scope"


def _cleanup_child_scope(p, unit):
    try:
        os.killpg(os.getpgid(p.pid), signal.SIGKILL)
    except ProcessLookupError:
        pass
    if not unit:
        return
    for cmd in (
        ["systemctl", "--user", "kill", "--signal=SIGKILL", unit],
        ["systemctl", "--user", "stop", unit],
    ):
        try:
            subprocess.run(
                cmd,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=5,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            pass


def run_timed(cmd, timeout, env=None):
    """Run cmd with a wall-clock timeout and a hard memory cap (systemd cgroup),
    in its own session so the whole process group can be killed.  Returns
    (rc, stderr, secs, timed_out)."""
    start = time.monotonic()
    child_cmd, unit = _prepare_child_cmd(cmd)
    p = subprocess.Popen(child_cmd, stdout=subprocess.DEVNULL,
                         stderr=subprocess.PIPE,
                         env=env, start_new_session=True)
    try:
        _, err = p.communicate(timeout=timeout)
        return p.returncode, err.decode("utf-8", "replace"), time.monotonic() - start, False
    except subprocess.TimeoutExpired:
        _cleanup_child_scope(p, unit)
        try:
            _, err = p.communicate(timeout=5)
        except subprocess.TimeoutExpired:
            _cleanup_child_scope(p, unit)
            err = b""
        return 124, (err or b"").decode("utf-8", "replace"), time.monotonic() - start, True


def run_capture(cmd, timeout, env=None):
    """Run cmd with captured stdout/stderr, the same timeout and memory cap as
    run_timed.  Returns (rc, stdout, stderr, secs, timed_out)."""
    start = time.monotonic()
    child_cmd, unit = _prepare_child_cmd(cmd)
    p = subprocess.Popen(child_cmd, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE, env=env,
                         start_new_session=True)
    try:
        out, err = p.communicate(timeout=timeout)
        return (p.returncode, out.decode("utf-8", "replace"),
                err.decode("utf-8", "replace"), time.monotonic() - start,
                False)
    except subprocess.TimeoutExpired:
        _cleanup_child_scope(p, unit)
        try:
            out, err = p.communicate(timeout=5)
        except subprocess.TimeoutExpired:
            _cleanup_child_scope(p, unit)
            out, err = b"", b""
        return (124, (out or b"").decode("utf-8", "replace"),
                (err or b"").decode("utf-8", "replace"),
                time.monotonic() - start, True)


def compose_cmd(args, *parts):
    return [args.tlsfcompose, *parts, *args.compose_extra_arg]


def solve_script_path():
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "solve.sh")


def default_solver_path():
    env = os.environ.get("ACACIA_BONSAI")
    if env:
        return env
    found = shutil.which("acacia-bonsai")
    if found:
        return found
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(
        here, "..", "..", "acacia-bonsai", "build_best_decomp_mona",
        "src", "acacia-bonsai"))


def classify_residual(reasons):
    """Pick the hardest residual class from a spec's cluster failure reasons."""
    joined = " ".join(reasons)
    if re.search(r"GR\([0-9]", joined):
        return "GR(2+) generalized reactivity"
    if "liveness" in joined or "unsupported temporal" in joined:
        return "liveness (F/U/GF/Buchi)"
    if "weak-until" in joined or "release safety" in joined:
        return "W/R safety not yet handled"
    if "no usable strategy" in joined:
        return "OxiDD miss"
    return "(none / unrealizable verdict)" if reasons == [] else "other"


def classify_structured_residual(external_rows, reasons):
    live = []
    for row in external_rows:
        cls = row.get("liveness_class", "")
        if row.get("has_liveness") == "1" and cls and cls != "none":
            live.append(cls)
    if live:
        priority = [
            "nested_unsupported",
            "mixed_buchi",
            "response",
            "gf_atom_or_bool",
            "eventual",
            "until",
            "unknown",
        ]
        for cls in priority:
            if cls in live:
                return "liveness: " + cls
        return "liveness: " + sorted(live)[0]
    return classify_residual(reasons)


def route_row_int(row, *keys, default=0):
    for key in keys:
        val = row.get(key, "")
        if val not in ("", "-", None):
            return int(val)
    return default


def route_row_uses_oxidd(row):
    val = row.get("uses_oxidd")
    if val in ("0", "1"):
        return val == "1"
    return row.get("backend", "").startswith("OxiDD")


def parse_route_stats(text):
    lines = [line for line in text.splitlines() if line.strip()]
    if not lines:
        return []
    return list(csv.DictReader(lines, delimiter="\t"))


def probe(spec, args):
    """Route diagnostics: which clusters match in-process route recognizers."""
    stats_cmd = compose_cmd(args, "--split", "--route-stats")
    stats_cmd.append(spec)
    s_rc, s_out, s_err, _, s_to = run_capture(stats_cmd, args.timeout)
    if s_to or s_rc != 0:
        return {
            "preprocessor_only": False,
            "oxidd_clusters": 0,
            "external_clusters": 0,
            "residual_class": classify_residual([s_err.strip()] if s_err.strip() else []),
            "full_nodes": 0,
            "external_nodes": 0,
            "full_bytes": 0,
            "external_bytes": 0,
            "max_outputs_any_cluster": 0,
            "max_outputs_external": 0,
        }

    rows = parse_route_stats(s_out)
    external_rows = [r for r in rows if not route_row_uses_oxidd(r)]
    oxidd_rows = [r for r in rows if route_row_uses_oxidd(r)]
    reasons = [r.get("reason", "") for r in external_rows if r.get("reason", "")]

    full_nodes = sum(route_row_int(r, "formula_nodes", "nodes") for r in rows)
    external_nodes = sum(
        route_row_int(r, "formula_nodes", "nodes") for r in external_rows
    )
    full_bytes = sum(route_row_int(r, "formula_bytes") for r in rows)
    external_bytes = sum(route_row_int(r, "formula_bytes") for r in external_rows)
    outputs = [route_row_int(r, "n_outputs", "n_outs") for r in rows]
    external_outputs = [
        route_row_int(r, "n_outputs", "n_outs") for r in external_rows
    ]

    return {
        "preprocessor_only": len(external_rows) == 0,
        "oxidd_clusters": len(oxidd_rows),
        "external_clusters": len(external_rows),
        "residual_class": classify_structured_residual(external_rows, reasons),
        "full_nodes": full_nodes,
        "external_nodes": external_nodes,
        "full_bytes": full_bytes,
        "external_bytes": external_bytes,
        "max_outputs_any_cluster": max(outputs) if outputs else 0,
        "max_outputs_external": max(external_outputs) if external_outputs else 0,
    }


def preproc_status(spec, args):
    env = dict(os.environ)
    with tempfile.TemporaryDirectory() as td:
        cmd = [
            solve_script_path(),
            "--tlsfcompose", args.tlsfcompose,
            "--backend", "acacia",
            "--solver", args.solver,
            "--output", os.path.join(td, "strategy.aag"),
            spec,
        ]
        rc, err, secs, to = run_timed(cmd, args.timeout, env)
    if to:
        st = "TIMEOUT"
    elif rc == 0:
        st = "SOLVED"
    elif "is UNREALIZABLE" in err:
        st = "UNREAL"
    elif "UNKNOWN" in err:
        st = "UNKNOWN"
    else:
        st = "FAILED"
    return st, secs


def sibling_tool(path, name):
    d = os.path.dirname(path)
    return os.path.join(d, name) if d else name


def absolutize_tool(path):
    if path and os.sep in path and not os.path.isabs(path):
        return os.path.abspath(path)
    return path


def parse_basic_signals(text):
    ins, outs, section = [], [], None
    for line in text.splitlines():
        s = line.split("//", 1)[0].strip()
        if s == "INPUTS {":
            section = "inputs"
            continue
        if s == "OUTPUTS {":
            section = "outputs"
            continue
        if section and s == "}":
            section = None
            continue
        if section and s.endswith(";"):
            name = s[:-1].strip()
            if name:
                (ins if section == "inputs" else outs).append(name)
    return ins, outs


def acacia_status_via_tlsf_tools(spec, args):
    start = time.monotonic()

    def remaining():
        return max(0.0, args.timeout - (time.monotonic() - start))

    try:
        basic = subprocess.run(
            [args.tlsf2tlsf, "--basic", spec],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=remaining(),
        )
    except subprocess.TimeoutExpired:
        return "TIMEOUT", time.monotonic() - start
    if basic.returncode != 0:
        return "ERROR", time.monotonic() - start
    ins, outs = parse_basic_signals(basic.stdout)
    if not outs:
        return "ERROR", time.monotonic() - start

    try:
        formula = subprocess.run(
            [args.tlsf2ltl, "--format", "ltlxba", spec],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=remaining(),
        )
    except subprocess.TimeoutExpired:
        return "TIMEOUT", time.monotonic() - start
    if formula.returncode != 0 or not formula.stdout.strip():
        return "ERROR", time.monotonic() - start

    tmp = None
    try:
        with tempfile.NamedTemporaryFile("w", suffix=".ltl", delete=False) as f:
            tmp = f.name
            f.write(formula.stdout.strip())
            f.write("\n")
        rem = remaining()
        if rem <= 0:
            return "TIMEOUT", time.monotonic() - start
        ins = [name.lower() for name in ins]
        outs = [name.lower() for name in outs]
        with tempfile.NamedTemporaryFile("w", suffix=".aag", delete=False) as sf:
            synth = sf.name
        cmd = [
            args.solver,
            "-F", tmp,
            "-i", ",".join(ins),
            "-o", ",".join(outs),
            "-s", synth,
        ]
        rc, _, _, to = run_timed(cmd, rem)
    finally:
        if tmp:
            try:
                os.unlink(tmp)
            except OSError:
                pass
        try:
            os.unlink(synth)
        except (NameError, OSError):
            pass
    secs = time.monotonic() - start
    if to:
        st = "TIMEOUT"
    elif rc == 0:
        st = "SOLVED"
    elif rc == 1:
        st = "UNREAL"
    elif rc == 2:
        st = "UNKNOWN"
    else:
        st = "ERROR"
    return st, secs


def acacia_status(spec, args):
    return acacia_status_via_tlsf_tools(spec, args)


def baseline_description(args):
    return ("`tlsf2tlsf --basic` + `tlsf2ltl --format ltlxba` + "
            "`acacia-bonsai -F ... -i ... -o ... -s ...`")


def load_rows(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        missing = [key for key in ROW_FIELDS if key not in (reader.fieldnames or [])]
        if missing:
            sys.exit(
                f"{path}: missing benchgraph columns: {', '.join(missing)}; "
                "rerun scripts/benchgraph.py with the current schema"
            )
        for raw in reader:
            r = {key: raw.get(key, "") for key in ROW_FIELDS}
            r["preprocessor_only"] = raw.get("preprocessor_only") == "1"
            for key in INT_FIELDS:
                r[key] = int(raw.get(key) or 0)
            for key in FLOAT_FIELDS:
                r[key] = float(raw.get(key) or 0.0)
            rows.append(r)
    return rows


def row_value(r, key):
    if key == "preprocessor_only":
        return int(r[key])
    if key in FLOAT_FIELDS and not r[key]:
        return ""
    return r[key]


def write_row(fp, r):
    fp.write("\t".join(str(row_value(r, key)) for key in ROW_FIELDS) + "\n")


def write_rows(path, rows):
    with open(path, "w", encoding="utf-8") as f:
        f.write("\t".join(ROW_FIELDS) + "\n")
        for r in rows:
            write_row(f, r)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--tlsfcompose", required=True)
    ap.add_argument("--solver", default=default_solver_path(),
                    help="acacia-bonsai binary path")
    ap.add_argument("--tlsf2ltl", default=None,
                    help="tlsf2ltl path for the standalone acacia translation")
    ap.add_argument("--tlsf2tlsf", default=None,
                    help="tlsf2tlsf path for the standalone acacia translation")
    ap.add_argument("--out", default="BENCHGRAPH.md")
    ap.add_argument("--data", default=None, help="per-spec TSV (default: alongside --out)")
    ap.add_argument("--timeout", type=int, default=10)
    ap.add_argument("--mem-gb", type=int, default=6,
                    help="hard per-run memory cap in GB (systemd cgroup); breach "
                         "kills only that child, not the box")
    ap.add_argument("--cap-label", default=None,
                    help="memory-cap text to record when re-rendering from data")
    ap.add_argument("--allow-uncapped", action="store_true",
                    help="run without the systemd memory cgroup when unavailable; "
                         "intended only for small smoke runs")
    ap.add_argument("--speed", choices=["routed", "all"], default="routed",
                    help="which specs to time (default: only route-contributing)")
    ap.add_argument("--compose-extra-arg", action="append", default=[],
                    help="extra argument passed to every tlsfcompose invocation; repeatable")
    ap.add_argument("--limit", type=int, default=0, help="cap #specs (0 = all; for smoke tests)")
    ap.add_argument("--from-data", default=None,
                    help="regenerate the report from an existing TSV (skip the corpus run)")
    ap.add_argument("--resume", action="store_true",
                    help="skip specs already present in --data (recover a crashed run)")
    ap.add_argument("--refresh-baseline-errors", action="store_true",
                    help="recompute acacia columns for timed rows whose standalone status is ERROR")
    args = ap.parse_args()
    args.tlsfcompose = absolutize_tool(args.tlsfcompose)
    args.solver = absolutize_tool(args.solver)
    data_path = args.data or (os.path.splitext(args.out)[0] + ".tsv")
    if args.tlsf2ltl is None:
        args.tlsf2ltl = sibling_tool(args.tlsfcompose, "tlsf2ltl")
    if args.tlsf2tlsf is None:
        args.tlsf2tlsf = sibling_tool(args.tlsfcompose, "tlsf2tlsf")
    args.tlsf2ltl = absolutize_tool(args.tlsf2ltl)
    args.tlsf2tlsf = absolutize_tool(args.tlsf2tlsf)

    global MEM_GB, FORCE_NO_CGROUP
    MEM_GB = args.mem_gb
    FORCE_NO_CGROUP = args.allow_uncapped

    if args.refresh_baseline_errors:
        rows = load_rows(data_path)
        for i, r in enumerate(rows, 1):
            if r["preproc_st"] and r["acacia_st"] == "ERROR":
                spec = os.path.join(args.corpus, r["name"])
                r["acacia_st"], r["acacia_t"] = acacia_status(spec, args)
            if i % 50 == 0 or i == len(rows):
                print(f"[{i}/{len(rows)}] baseline refresh", file=sys.stderr, flush=True)
        write_rows(data_path, rows)
        write_report(args, rows, len(rows), data_path)
        print(f"refreshed baseline columns in {data_path} and {args.out}",
              file=sys.stderr)
        return

    if args.from_data:
        rows = load_rows(args.from_data)
        write_report(args, rows, len(rows), args.from_data)
        print(f"regenerated {args.out} from {args.from_data}", file=sys.stderr)
        return

    if not HAVE_SYSTEMD_RUN and not FORCE_NO_CGROUP:
        sys.exit("error: systemd-run is not available/usable; a corpus run "
                 "would be UNPROTECTED against OOM.  Install/configure "
                 "systemd-run, use --from-data to re-render, or pass "
                 "--allow-uncapped for a small smoke run.")

    specs = []
    for root, _, files in os.walk(args.corpus):
        for f in files:
            if f.endswith(".tlsf"):
                specs.append(os.path.join(root, f))
    specs.sort()
    if args.limit:
        specs = specs[:args.limit]
    total = len(specs)

    # Rows are written incrementally (append + flush) so a crash mid-run -- e.g.
    # the OOM killer on a memory-hungry spec -- loses nothing and `--resume`
    # continues.
    header = "\t".join(ROW_FIELDS) + "\n"
    done = set()
    if args.resume and os.path.exists(data_path):
        done = {r["name"] for r in load_rows(data_path)}
        f = open(data_path, "a")
    else:
        f = open(data_path, "w")
        f.write(header)
    f.flush()

    t0 = time.monotonic()
    for i, spec in enumerate(specs, 1):
        name = os.path.relpath(spec, args.corpus)
        if name in done:
            continue
        pr = probe(spec, args)
        do_speed = args.speed == "all" or pr["oxidd_clusters"] > 0
        preproc = acacia = ("", "")
        if do_speed:
            preproc = preproc_status(spec, args)
            acacia = acacia_status(spec, args)
        write_row(f, {
            "name": name,
            **pr,
            "preproc_st": preproc[0],
            "preproc_t": preproc[1] or 0.0,
            "acacia_st": acacia[0],
            "acacia_t": acacia[1] or 0.0,
        })
        f.flush()
        if i % 50 == 0 or i == total:
            el = time.monotonic() - t0
            print(f"[{i}/{total}] {el:.0f}s elapsed", file=sys.stderr, flush=True)
    f.close()

    rows = load_rows(data_path)
    write_report(args, rows, total, data_path)
    print(f"wrote {args.out} and {data_path}", file=sys.stderr)


def write_survival_plot(rows, png_path, timeout):
    """Cactus/survival plot: for each engine, the i-th fastest definitive solve.
    A curve further RIGHT solves more instances; LOWER means faster.  "Solved" =
    produced a controller (SOLVED) or a verdict (UNREAL) within the timeout."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return False

    def solved_times(st_key, t_key):
        return sorted(r[t_key] for r in rows
                      if r[st_key] in ("SOLVED", "UNREAL") and r[t_key] > 0)

    base = solved_times("acacia_st", "acacia_t")
    preproc = solved_times("preproc_st", "preproc_t")
    if not base and not preproc:
        return False
    fig, ax = plt.subplots(figsize=(7.2, 4.4))
    ax.step(range(1, len(base) + 1), base, where="post", color="#c44e52",
            lw=1.8, label=f"acacia-bonsai ({len(base)} solved)")
    ax.step(range(1, len(preproc) + 1), preproc, where="post", color="#4c72b0",
            lw=1.8, label=f"preprocessor + acacia-bonsai ({len(preproc)} solved)")
    ax.axhline(timeout, color="k", lw=0.8, ls="--")
    ax.set_yscale("log")
    ax.set_xlabel("instances solved (cumulative)")
    ax.set_ylabel("time per instance (s, log)")
    ax.set_title("Survival: acacia-bonsai vs preprocessor + acacia-bonsai")
    ax.grid(True, which="both", ls=":", lw=0.4, alpha=0.5)
    ax.legend(loc="upper left", fontsize=9)
    fig.tight_layout()
    os.makedirs(os.path.dirname(png_path), exist_ok=True)
    fig.savefig(png_path, dpi=120)
    plt.close(fig)
    return True


def write_report(args, rows, total, data_path):
    from collections import Counter
    preprocessor_only = [r for r in rows if r["preprocessor_only"]]
    timed = [r for r in rows if r["preproc_st"]]

    def ok(st):
        return st in ("SOLVED", "UNREAL")  # definitive answer within timeout

    both = [r for r in timed if ok(r["preproc_st"]) and ok(r["acacia_st"])]
    only_preproc = [r for r in timed if ok(r["preproc_st"]) and not ok(r["acacia_st"])]
    only_acacia = [r for r in timed if ok(r["acacia_st"]) and not ok(r["preproc_st"])]
    neither = [r for r in timed if not ok(r["preproc_st"]) and not ok(r["acacia_st"])]
    n_preproc = sum(1 for r in timed if ok(r["preproc_st"]))
    n_acacia = sum(1 for r in timed if ok(r["acacia_st"]))
    # Wall-time speedup where BOTH produced a controller (fair comparison).
    both_ctrl = [r for r in timed if r["preproc_st"] == "SOLVED"
                 and r["acacia_st"] == "SOLVED" and r["preproc_t"] > 1e-6]
    speedups = [r["acacia_t"] / r["preproc_t"] for r in both_ctrl]
    sum_preproc = sum(r["preproc_t"] for r in both_ctrl)
    sum_acacia = sum(r["acacia_t"] for r in both_ctrl)
    preproc_unreal_acacia_solved = [
        r for r in timed if r["preproc_st"] == "UNREAL" and r["acacia_st"] == "SOLVED"
    ]
    preproc_solved_acacia_unreal = [
        r for r in timed if r["preproc_st"] == "SOLVED" and r["acacia_st"] == "UNREAL"
    ]
    win_fam = Counter(os.path.dirname(r["name"]) or "." for r in only_preproc)

    def fam_summary(counter):
        parts = [f"{d.split('/')[-1]}×{n}" for d, n in counter.most_common()
                 if d != "."]
        return ", ".join(parts[:6])

    png_rel = "docs/benchgraph/survival.png"
    png_abs = os.path.join(os.path.dirname(os.path.abspath(args.out)) or ".",
                           png_rel)
    have_plot = write_survival_plot(timed, png_abs, args.timeout)

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True).stdout.strip()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    def med(xs):
        return statistics.median(xs) if xs else float("nan")

    def geo(xs):
        return statistics.geometric_mean(xs) if xs else float("nan")

    cap_how = args.cap_label or (
        "UNENFORCED (--allow-uncapped)" if FORCE_NO_CGROUP else
        "systemd cgroup hard cap" if HAVE_SYSTEMD_RUN else
        "UNENFORCED (no usable systemd-run)"
    )

    L = []
    L.append(SENTINEL_START + "\n")
    L.append("## acacia-bonsai vs preprocessor + acacia-bonsai (`scripts/benchgraph.py`)\n")
    L.append("Head-to-head synthesis: standalone **acacia-bonsai** vs the **preprocessor** "
             "(`--split` decomposition + one persistent OxiDD residual-solving "
             "phase + external residual merge). Trusted exact/UNDER controller "
             "routes and trusted OVER UNREAL routes finish in process; remaining "
             "exact residual clusters go to acacia-bonsai. Each (engine, spec) "
             "pair gets the same timeout. Regenerate with `scripts/benchgraph.py` (or "
             "`--from-data benchgraph.tsv` to re-render).\n")
    L.append(f"\n### Run: {now} · commit `{commit}`\n")
    L.append(f"- Corpus `{args.corpus}` ({total} specs); timeout **{args.timeout}s**, "
             f"{MEM_GB} GB/run ({cap_how}), sequential.\n"
             f"- acacia-bonsai: {baseline_description(args)}\n"
             f"- preprocessor + acacia-bonsai: "
             f"`scripts/solve.sh --backend acacia --solver ...`"
             + (f" {' '.join(args.compose_extra_arg)}" if args.compose_extra_arg else "")
             + f"\n- Specs completed without an external residual solver: "
             f"**{len(preprocessor_only)}/{total} = "
             f"{100*len(preprocessor_only)/total:.1f}%**.\n")

    L.append("\n### Solved within timeout\n")
    L.append(f"| engine | solved | only this engine |\n|---|--:|--:|\n")
    L.append(f"| acacia-bonsai | {n_acacia}/{len(timed)} | {len(only_acacia)} |\n")
    L.append(f"| preprocessor + acacia-bonsai | "
             f"{n_preproc}/{len(timed)} | {len(only_preproc)} |\n")
    net = n_preproc - n_acacia
    L.append(f"\n- Both: {len(both)}; neither: {len(neither)}. "
             f"**Net gain from the preprocessor: {net:+d}** "
             f"({len(only_preproc)} won, {len(only_acacia)} lost).\n")
    if win_fam:
        L.append(f"- Preprocessor-only solves by family: {fam_summary(win_fam)}.\n")

    if speedups:
        L.append("\n### Speed (both produced a controller)\n")
        L.append(f"- {len(both_ctrl)} specs both SOLVED. "
                 f"**Speedup `acacia/preproc`: median ×{med(speedups):.2f}, "
                 f"geomean ×{geo(speedups):.2f}** "
                 f"(faster {sum(1 for s in speedups if s>1)}, "
                 f"slower {sum(1 for s in speedups if s<1)}); "
                 f"aggregate wall ×{sum_acacia/sum_preproc:.2f}.\n")

    if have_plot:
        L.append(f"\n![Survival: acacia-bonsai vs preprocessor + acacia-bonsai]({png_rel})\n")

    if preproc_unreal_acacia_solved or preproc_solved_acacia_unreal:
        L.append(f"\n- Verdict disagreements against standalone acacia-bonsai: "
                 f"{len(preproc_unreal_acacia_solved)} preprocessor-UNREAL/acacia-SOLVED, "
                 f"{len(preproc_solved_acacia_unreal)} preprocessor-SOLVED/acacia-UNREAL.\n")
    L.append(SENTINEL_END + "\n")
    section = "".join(L)

    # Inject as a self-delimited section: replace between the sentinels if they
    # already exist (so reruns only touch this section), else append to the doc.
    existing = ""
    if os.path.exists(args.out):
        with open(args.out) as f:
            existing = f.read()
    if SENTINEL_START in existing and SENTINEL_END in existing:
        pre = existing[:existing.index(SENTINEL_START)]
        post = existing[existing.index(SENTINEL_END) + len(SENTINEL_END):]
        new = pre + section.rstrip("\n") + post
    elif existing.strip():
        new = existing.rstrip("\n") + "\n\n" + section
    else:
        new = "# BENCHGRAPH\n\n" + section
    with open(args.out, "w") as f:
        f.write(new)


if __name__ == "__main__":
    main()
