#!/usr/bin/env python3
"""Benchmark tlsf-tools (templates + OxiDD) as a FAST preprocessor for
synthesis, against standalone ltlsynt.

Two metrics, both rerunnable over the corpus and summarised into BENCHGRAPH.md:

  COMPLEXITY (whole corpus, ltlsynt disabled): how many specs are fully
  self-contained via templates+OxiDD, and what shape are the residual
  clusters that still need a liveness backend.

  SPEED (focus: specs where OxiDD handles >=1 cluster): wall time of the full
  tlsf-tools pipeline (templates + OxiDD + ltlsynt on residuals) vs a standalone
  `ltlsynt` baseline for the whole spec.  Solve STATUS is tracked too -- a fast
  failure is not a speedup, so speedups are only computed where both engines
  actually produced a controller.

Usage:
  scripts/benchgraph.py --corpus DIR --tlsfcompose PATH \
      --ltlsynt PATH [--out BENCHGRAPH.md] [--data data.tsv] \
      [--timeout 15] [--mem-gb 8] [--speed all|oxidd]
"""
import argparse
import os
import shutil
import signal
import statistics
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timezone

# Per-child memory cap, enforced via a systemd transient scope (cgroup) -- set
# from --mem-gb in main().  RLIMIT_AS cannot be used: OxiDD reserves large
# virtual pools (>6 GB) even for tiny games, causing spurious SIGABRT panics; and
# RLIMIT_RSS is advisory-only on Linux.  A `systemd-run --user --scope` cgroup
# with MemoryMax + MemorySwapMax=0 gives a *hard* RSS+swap cap whose breach kills
# only that child's cgroup (verified), never the whole box -- which an unenforced
# cap previously let the OS OOM killer do.
MEM_GB = 6
HAVE_SYSTEMD_RUN = shutil.which("systemd-run") is not None
SENTINEL_START = "<!-- BENCHGRAPH:PREPROCESSOR START (generated by scripts/benchgraph.py) -->"
SENTINEL_END = "<!-- BENCHGRAPH:PREPROCESSOR END -->"


def _mem_wrap(cmd):
    """Prepend a systemd transient-scope cgroup with a hard memory cap.  --quiet
    keeps the child's stderr clean (we parse it); --collect reaps the unit even
    on failure; MemorySwapMax=0 stops the child eating (zram) swap."""
    if not HAVE_SYSTEMD_RUN:
        return cmd
    return ["systemd-run", "--user", "--scope", "--quiet", "--collect",
            "-p", f"MemoryMax={MEM_GB}G", "-p", "MemorySwapMax=0",
            "--"] + list(cmd)


def run_timed(cmd, timeout, env=None):
    """Run cmd with a wall-clock timeout and a hard memory cap (systemd cgroup),
    in its own session so the whole process group can be killed.  Returns
    (rc, stderr, secs, timed_out)."""
    start = time.monotonic()
    p = subprocess.Popen(_mem_wrap(cmd), stdout=subprocess.DEVNULL,
                         stderr=subprocess.PIPE,
                         env=env, start_new_session=True)
    try:
        _, err = p.communicate(timeout=timeout)
        return p.returncode, err.decode("utf-8", "replace"), time.monotonic() - start, False
    except subprocess.TimeoutExpired:
        try:
            os.killpg(os.getpgid(p.pid), signal.SIGKILL)
        except ProcessLookupError:
            pass
        try:
            _, err = p.communicate(timeout=5)
        except subprocess.TimeoutExpired:
            err = b""
        return 124, (err or b"").decode("utf-8", "replace"), time.monotonic() - start, True


def classify_residual(reasons):
    """Pick the hardest residual class from a spec's cluster failure reasons."""
    joined = " ".join(reasons)
    import re
    if re.search(r"GR\([0-9]", joined):
        return "GR(2+) generalized reactivity"
    if "liveness" in joined or "unsupported temporal" in joined:
        return "liveness (F/U/GF/Buchi)"
    if "weak-until" in joined or "release safety" in joined:
        return "W/R safety not yet handled"
    if "no usable strategy" in joined:
        return "OxiDD miss"
    return "(none / unrealizable verdict)" if reasons == [] else "other"


def probe(spec, args):
    """ltlsynt-disabled run: self-contained? which OxiDD backends? residual shape."""
    env = dict(os.environ, TLSFCOMPOSE_DEBUG="1")
    cmd = [args.tlsfcompose, "--split", "--aiger",
           "--ltlsynt", "/bin/false", spec]
    rc, err, _, _ = run_timed(cmd, args.timeout, env)
    routes, reasons, unreal = [], [], 0
    for line in err.splitlines():
        if "routed to " in line:
            backend = line.split("routed to ", 1)[1]
            nodes = 0
            if "nodes=" in line:  # per-cluster residual formula size
                tok = line.split("nodes=", 1)[1].split(" ", 1)[0]
                nodes = int(tok) if tok.isdigit() else 0
            routes.append((nodes, backend))
        elif "synthesis backend failed for cluster" in line and "(" in line:
            inner = line[line.index("(") + 1:line.rindex(")")]
            reasons.append(inner.split(": ", 1)[1] if ": " in inner else inner)
        elif "is UNREALIZABLE" in line:
            unreal += 1
    # A cluster routed to a backend starting with "OxiDD" was peeled in-process;
    # anything else is forwarded to ltlsynt (liveness/GR(1)/OxiDD-miss fallback).
    oxidd = [n for n, b in routes if b.startswith("OxiDD")]
    ltl = [n for n, b in routes if not b.startswith("OxiDD")]
    return {
        "self_contained": rc == 0,
        "abs_clusters": len(oxidd),
        "residual_class": classify_residual(reasons),
        "probe_unreal": unreal,
        "full_nodes": sum(oxidd) + sum(ltl),   # all synthesis clusters
        "residual_nodes": sum(ltl),            # forwarded to ltlsynt
        "n_oxidd": len(oxidd),
        "n_ltlsynt": len(ltl),
    }


def ours_status(spec, args):
    env = dict(os.environ)
    cmd = [args.tlsfcompose, "--split", "--aiger",
           "--ltlsynt", args.ltlsynt, spec]
    rc, err, secs, to = run_timed(cmd, args.timeout, env)
    if to:
        st = "TIMEOUT"
    elif rc == 0:
        st = "SOLVED"
    elif "is UNREALIZABLE" in err:
        st = "UNREAL"
    else:
        st = "FAILED"
    return st, secs


def sibling_tool(path, name):
    d = os.path.dirname(path)
    return os.path.join(d, name) if d else name


def parse_basic_signals(text):
    ins, outs, section = [], [], None
    for line in text.splitlines():
        s = line.split("//", 1)[0].strip()
        if s == "INPUTS {":
            section = "inputs"
            continue
        if s == "OUTPUTS {":
            section = "outputs"
            continue
        if section and s == "}":
            section = None
            continue
        if section and s.endswith(";"):
            name = s[:-1].strip()
            if name:
                (ins if section == "inputs" else outs).append(name)
    return ins, outs


def base_status_via_tlsf_tools(spec, args):
    start = time.monotonic()

    def remaining():
        return max(0.0, args.timeout - (time.monotonic() - start))

    try:
        basic = subprocess.run(
            [args.tlsf2tlsf, "--basic", spec],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=remaining(),
        )
    except subprocess.TimeoutExpired:
        return "TIMEOUT", time.monotonic() - start
    if basic.returncode != 0:
        return "ERROR", time.monotonic() - start
    ins, outs = parse_basic_signals(basic.stdout)
    if not outs:
        return "ERROR", time.monotonic() - start

    try:
        formula = subprocess.run(
            [args.tlsf2ltl, "--format", "ltl", spec],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=remaining(),
        )
    except subprocess.TimeoutExpired:
        return "TIMEOUT", time.monotonic() - start
    if formula.returncode != 0 or not formula.stdout.strip():
        return "ERROR", time.monotonic() - start

    tmp = None
    try:
        with tempfile.NamedTemporaryFile("w", suffix=".ltl", delete=False) as f:
            tmp = f.name
            f.write(formula.stdout.strip())
            f.write("\n")
        rem = remaining()
        if rem <= 0:
            return "TIMEOUT", time.monotonic() - start
        cmd = [args.ltlsynt, "-F", tmp, "--outs", ",".join(outs), "--aiger"]
        if ins:
            cmd += ["--ins", ",".join(ins)]
        rc, _, _, to = run_timed(cmd, rem)
    finally:
        if tmp:
            try:
                os.unlink(tmp)
            except OSError:
                pass
    secs = time.monotonic() - start
    if to:
        st = "TIMEOUT"
    elif rc == 0:
        st = "SOLVED"
    elif rc == 1:
        st = "UNREAL"
    else:
        st = "ERROR"
    return st, secs


def base_status(spec, args):
    if args.baseline_mode == "tlsf-tools":
        return base_status_via_tlsf_tools(spec, args)
    rc, _, secs, to = run_timed([args.ltlsynt, "--tlsf=" + spec, "--aiger"], args.timeout)
    if to:
        st = "TIMEOUT"
    elif rc == 0:
        st = "SOLVED"
    elif rc == 1:
        st = "UNREAL"
    else:
        st = "ERROR"
    return st, secs


def baseline_description(args):
    if args.baseline_mode == "tlsf-tools":
        return ("`tlsf2tlsf --basic` + `tlsf2ltl --format ltl` + "
                "`ltlsynt -F … --ins … --outs … --aiger`")
    return "`ltlsynt --tlsf=SPEC --aiger` (syfco translation, full synthesis)"


def load_rows(path):
    rows = []
    with open(path) as f:
        next(f)
        for line in f:
            p = line.rstrip("\n").split("\t")
            r = {
                "name": p[0], "self_contained": p[1] == "1", "abs_clusters": int(p[2]),
                "residual_class": p[3], "ours_st": p[4],
                "ours_t": float(p[5]) if p[5] else 0.0, "base_st": p[6],
                "base_t": float(p[7]) if p[7] else 0.0,
            }
            # Residual-reduction columns (added later; tolerate older TSVs).
            r["full_nodes"] = int(p[8]) if len(p) > 8 and p[8] else 0
            r["residual_nodes"] = int(p[9]) if len(p) > 9 and p[9] else 0
            r["n_oxidd"] = int(p[10]) if len(p) > 10 and p[10] else 0
            r["n_ltlsynt"] = int(p[11]) if len(p) > 11 and p[11] else 0
            rows.append(r)
    return rows


def write_rows(path, rows):
    with open(path, "w") as f:
        f.write("name\tself_contained\tabs_clusters\tresidual_class\t"
                "ours_st\tours_t\tbase_st\tbase_t\t"
                "full_nodes\tresidual_nodes\tn_oxidd\tn_ltlsynt\n")
        for r in rows:
            f.write(f"{r['name']}\t{int(r['self_contained'])}\t"
                    f"{r['abs_clusters']}\t{r['residual_class']}\t"
                    f"{r['ours_st']}\t{r['ours_t'] or ''}\t"
                    f"{r['base_st']}\t{r['base_t'] or ''}\t"
                    f"{r['full_nodes']}\t{r['residual_nodes']}\t"
                    f"{r['n_oxidd']}\t{r['n_ltlsynt']}\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--tlsfcompose", required=True)
    ap.add_argument("--ltlsynt", default=shutil.which("ltlsynt") or "ltlsynt")
    ap.add_argument("--tlsf2ltl", default=None,
                    help="tlsf2ltl path for syfco-free baseline mode")
    ap.add_argument("--tlsf2tlsf", default=None,
                    help="tlsf2tlsf path for syfco-free baseline mode")
    ap.add_argument("--baseline-mode", choices=["auto", "syfco", "tlsf-tools"],
                    default="auto",
                    help="baseline translation path for standalone ltlsynt")
    ap.add_argument("--out", default="BENCHGRAPH.md")
    ap.add_argument("--data", default=None, help="per-spec TSV (default: alongside --out)")
    ap.add_argument("--timeout", type=int, default=15)
    ap.add_argument("--mem-gb", type=int, default=6,
                    help="hard per-run memory cap in GB (systemd cgroup); breach "
                         "kills only that child, not the box")
    ap.add_argument("--speed", choices=["oxidd", "all"], default="oxidd",
                    help="which specs to time (default: only OxiDD-contributing)")
    ap.add_argument("--limit", type=int, default=0, help="cap #specs (0 = all; for smoke tests)")
    ap.add_argument("--from-data", default=None,
                    help="regenerate the report from an existing TSV (skip the corpus run)")
    ap.add_argument("--resume", action="store_true",
                    help="skip specs already present in --data (recover a crashed run)")
    ap.add_argument("--refresh-baseline-errors", action="store_true",
                    help="recompute baseline columns for timed rows whose baseline status is ERROR")
    args = ap.parse_args()
    data_path = args.data or (os.path.splitext(args.out)[0] + ".tsv")
    if args.tlsf2ltl is None:
        args.tlsf2ltl = sibling_tool(args.tlsfcompose, "tlsf2ltl")
    if args.tlsf2tlsf is None:
        args.tlsf2tlsf = sibling_tool(args.tlsfcompose, "tlsf2tlsf")
    if args.baseline_mode == "auto":
        args.baseline_mode = "syfco" if shutil.which("syfco") else "tlsf-tools"

    global MEM_GB
    MEM_GB = args.mem_gb

    if args.refresh_baseline_errors:
        rows = load_rows(data_path)
        for i, r in enumerate(rows, 1):
            if r["ours_st"] and r["base_st"] == "ERROR":
                spec = os.path.join(args.corpus, r["name"])
                r["base_st"], r["base_t"] = base_status(spec, args)
            if i % 50 == 0 or i == len(rows):
                print(f"[{i}/{len(rows)}] baseline refresh", file=sys.stderr, flush=True)
        write_rows(data_path, rows)
        write_report(args, rows, len(rows), data_path)
        print(f"refreshed baseline columns in {data_path} and {args.out}",
              file=sys.stderr)
        return

    if args.from_data:
        rows = load_rows(args.from_data)
        write_report(args, rows, len(rows), args.from_data)
        print(f"regenerated {args.out} from {args.from_data}", file=sys.stderr)
        return

    if not HAVE_SYSTEMD_RUN:
        sys.exit("error: systemd-run not found; a corpus run would be UNPROTECTED "
                 "against OOM.  Install systemd-run or use --from-data to re-render.")

    specs = []
    for root, _, files in os.walk(args.corpus):
        for f in files:
            if f.endswith(".tlsf"):
                specs.append(os.path.join(root, f))
    specs.sort()
    if args.limit:
        specs = specs[:args.limit]
    total = len(specs)

    # Rows are written incrementally (append + flush) so a crash mid-run -- e.g.
    # the OOM killer on a memory-hungry spec -- loses nothing and `--resume`
    # continues.
    header = ("name\tself_contained\tabs_clusters\tresidual_class\t"
              "ours_st\tours_t\tbase_st\tbase_t\t"
              "full_nodes\tresidual_nodes\tn_oxidd\tn_ltlsynt\n")
    done = set()
    if args.resume and os.path.exists(data_path):
        done = {r["name"] for r in load_rows(data_path)}
        f = open(data_path, "a")
    else:
        f = open(data_path, "w")
        f.write(header)
    f.flush()

    t0 = time.monotonic()
    for i, spec in enumerate(specs, 1):
        name = os.path.relpath(spec, args.corpus)
        if name in done:
            continue
        pr = probe(spec, args)
        do_speed = args.speed == "all" or pr["abs_clusters"] > 0
        ours = base = ("", "")
        if do_speed:
            ours = ours_status(spec, args)
            base = base_status(spec, args)
        f.write(f"{name}\t{int(pr['self_contained'])}\t{pr['abs_clusters']}\t"
                f"{pr['residual_class']}\t{ours[0]}\t{ours[1] or ''}\t"
                f"{base[0]}\t{base[1] or ''}\t"
                f"{pr['full_nodes']}\t{pr['residual_nodes']}\t"
                f"{pr['n_oxidd']}\t{pr['n_ltlsynt']}\n")
        f.flush()
        if i % 50 == 0 or i == total:
            el = time.monotonic() - t0
            print(f"[{i}/{total}] {el:.0f}s elapsed", file=sys.stderr, flush=True)
    f.close()

    rows = load_rows(data_path)
    write_report(args, rows, total, data_path)
    print(f"wrote {args.out} and {data_path}", file=sys.stderr)


def write_report(args, rows, total, data_path):
    sc = [r for r in rows if r["self_contained"]]
    sc_abs = [r for r in sc if r["abs_clusters"] > 0]
    reach = [r for r in rows if r["abs_clusters"] > 0]
    # complexity: residual class among non-self-contained
    from collections import Counter
    resid = Counter(r["residual_class"] for r in rows if not r["self_contained"])

    # speed: only specs we actually timed
    timed = [r for r in rows if r["ours_st"]]
    both = [r for r in timed if r["ours_st"] == "SOLVED" and r["base_st"] == "SOLVED"]
    speedups = [r["base_t"] / r["ours_t"] for r in both if r["ours_t"] > 1e-6]
    ours_win_base_to = [r for r in timed if r["ours_st"] == "SOLVED" and r["base_st"] == "TIMEOUT"]
    gap = [r for r in timed if r["ours_st"] == "FAILED" and r["base_st"] == "SOLVED"]
    ours_to = [r for r in timed if r["ours_st"] == "TIMEOUT" and r["base_st"] == "SOLVED"]
    false_unreal = [r for r in timed if r["ours_st"] == "UNREAL" and r["base_st"] == "SOLVED"]
    ours_statuses = Counter(r["ours_st"] for r in timed)
    base_statuses = Counter(r["base_st"] for r in timed)
    # the honest completeness deficit: ltlsynt produced a controller, we did not
    less_complete = gap + false_unreal + ours_to
    sum_ours = sum(r["ours_t"] for r in both)
    sum_base = sum(r["base_t"] for r in both)

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True).stdout.strip()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    def med(xs):
        return statistics.median(xs) if xs else float("nan")

    def geo(xs):
        return statistics.geometric_mean(xs) if xs else float("nan")

    L = []
    L.append(SENTINEL_START + "\n")
    L.append("## Preprocessor speed & complexity vs ltlsynt (`scripts/benchgraph.py`)\n")
    L.append("Is templates+OxiDD a FAST preprocessor? Two metrics: residual **complexity**\n"
             "(what's left after templates+OxiDD) and **speed** (our full pipeline vs a standalone\n"
             "`ltlsynt` baseline for the whole spec). Goal: carve off safety with OxiDD, forward\n"
             "only the hard liveness residual to ltlsynt, and never be slower or less complete.\n"
             "Regenerate: `scripts/benchgraph.py --corpus DIR --tlsfcompose … --ltlsynt …`\n"
             "(or `--from-data benchgraph.tsv` to re-render this section without re-running).\n")
    L.append(f"\n### Run: {now} · commit `{commit}`\n")
    cap_how = "systemd cgroup hard cap" if HAVE_SYSTEMD_RUN else "UNENFORCED (no systemd-run)"
    L.append(f"- Corpus: `{args.corpus}` ({total} specs)\n"
             f"- Caps: timeout {args.timeout}s/run, "
             f"{MEM_GB} GB RAM/run ({cap_how}), sequential\n"
             f"- Baseline: {baseline_description(args)}\n"
             f"- Ours: `tlsfcompose --split --aiger --ltlsynt …`\n"
             f"- Per-spec data: `{os.path.basename(data_path)}`\n")

    L.append("\n### Complexity\n")
    L.append(f"- **Self-contained (templates+OxiDD, no ltlsynt): {len(sc)}/{total} "
             f"= {100*len(sc)/total:.1f}%** ({len(sc_abs)} use OxiDD).\n")
    L.append(f"- **OxiDD reach (≥1 cluster): {len(reach)}/{total} = {100*len(reach)/total:.1f}%**.\n")
    L.append("- Residual shape (specs not self-contained), hardest cluster:\n\n")
    L.append("  | residual class | specs |\n  |---|---|\n")
    for cls, n in resid.most_common():
        L.append(f"  | {cls} | {n} |\n")

    # Residual reduction: of the synthesis clusters that survive templating, how
    # much formula mass (node count) OxiDD peels off before ltlsynt.  A cluster
    # routed to "OxiDD*" is solved in-process; everything else is forwarded.
    nz = [r for r in rows if r["full_nodes"] > 0]
    L.append("\n### Residual reduction (complexity)\n")
    if nz:
        tot_full = sum(r["full_nodes"] for r in nz)
        tot_resid = sum(r["residual_nodes"] for r in nz)
        n_ox = sum(r["n_oxidd"] for r in nz)
        n_lt = sum(r["n_ltlsynt"] for r in nz)
        carved_per = [1 - r["residual_nodes"] / r["full_nodes"] for r in nz]
        fully = sum(1 for r in nz if r["residual_nodes"] == 0)
        agg = 1 - tot_resid / tot_full if tot_full else float("nan")
        dist = Counter(r["n_ltlsynt"] for r in nz)
        L.append(f"- Specs with ≥1 synthesis cluster: {len(nz)}; "
                 f"{n_ox + n_lt} clusters total "
                 f"({n_ox} peeled by OxiDD, {n_lt} forwarded to ltlsynt).\n")
        L.append(f"- **Formula mass OxiDD carves off the residual before ltlsynt: "
                 f"aggregate {100*agg:.1f}%** "
                 f"(residual {tot_resid}/{tot_full} nodes), "
                 f"median per spec **{100*med(carved_per):.1f}%**.\n")
        L.append(f"- OxiDD peels the **entire** synthesis residual (nothing left "
                 f"for ltlsynt): {fully}/{len(nz)} specs.\n")
        L.append("- Residual clusters still forwarded to ltlsynt (count → specs): "
                 + ", ".join(f"{k}→{v}" for k, v in sorted(dist.items())) + ".\n")
    else:
        L.append("- (no per-cluster node data in this dataset — re-run the corpus "
                 "with an instrumented `tlsfcompose`)\n")

    med_ours = med([r["ours_t"] for r in both])
    med_base = med([r["base_t"] for r in both])
    from collections import Counter
    win_fam = Counter(os.path.dirname(r["name"]) or "." for r in ours_win_base_to)
    gap_fam = Counter(os.path.dirname(r["name"]) or "." for r in gap)

    def fam_summary(counter):
        parts = []
        for d, n in counter.most_common():
            if d == ".":
                continue
            parts.append(f"{d.split('/')[-1]}×{n}")
        return ", ".join(parts)

    L.append("\n### Speed (OxiDD-contributing specs)\n")
    L.append(f"- Timed: {len(timed)} specs. Both produced a controller: {len(both)}.\n")
    if timed:
        L.append("- Status breakdown on timed specs: "
                 f"ours SOLVED {ours_statuses['SOLVED']}, "
                 f"UNREAL {ours_statuses['UNREAL']}, "
                 f"TIMEOUT {ours_statuses['TIMEOUT']}, "
                 f"FAILED {ours_statuses['FAILED']}; "
                 f"baseline SOLVED {base_statuses['SOLVED']}, "
                 f"UNREAL {base_statuses['UNREAL']}, "
                 f"TIMEOUT {base_statuses['TIMEOUT']}, "
                 f"ERROR {base_statuses['ERROR']}.\n")
    if base_statuses["ERROR"]:
        L.append("- Baseline ERROR rows are excluded from speedup statistics; "
                 "they are cases where standalone `ltlsynt` did not produce a "
                 "verdict for the expanded formula/signals.\n")
    if speedups:
        L.append(f"- **Both-solved speedup `base/ours`: median ×{med(speedups):.2f}, "
                 f"geomean ×{geo(speedups):.2f}** "
                 f"(faster: {sum(1 for s in speedups if s>1)}, slower: {sum(1 for s in speedups if s<1)}).\n")
        L.append(f"- Absolute wall on both-solved: **median ours {med_ours*1000:.0f} ms vs base "
                 f"{med_base*1000:.0f} ms** (near parity); mean ours {sum_ours/len(both)*1000:.0f} ms "
                 f"vs base {sum_base/len(both)*1000:.0f} ms.\n")
        L.append(f"- Total wall on both-solved: ours {sum_ours:.1f}s vs base {sum_base:.1f}s "
                 f"(**×{sum_base/sum_ours:.2f}** aggregate).\n")
    wins_word = "win" if len(ours_win_base_to) == 1 else "wins"
    win_fams = fam_summary(win_fam)
    L.append(f"- Ours solves where **base times out** (≥{args.timeout}s): {len(ours_win_base_to)} clear {wins_word}"
             + (f" — {win_fams}" if win_fams else "")
             + ".\n")

    fu_fam = Counter(os.path.dirname(r["name"]) or "." for r in false_unreal)
    L.append("\n### Completeness vs ltlsynt\n")
    L.append(f"- **ltlsynt produced a controller but we did not: {len(less_complete)}** — the honest "
             f"deficit (we are *less complete* on these). Breakdown: {len(false_unreal)} we wrongly call "
             f"**UNREALIZABLE**, {len(gap)} backend **FAILED**, {len(ours_to)} **timed out**.\n")
    if fu_fam:
        L.append("- The false-UNREALs are dominated by "
                 + ", ".join(f"{d.split('/')[-1] or d}×{n}" for d, n in fu_fam.most_common(4))
                 + " — output-free assumption clusters synthesised standalone.\n")

    L.append("\n### Verdict\n")
    if both:
        agg = sum_base / sum_ours if sum_ours else float("nan")
        agg_dir = "faster" if agg >= 1 else "slower"
        L.append(
            f"On the **median** OxiDD-contributing spec where both engines synthesize, tlsf-tools is "
            f"at **rough parity** ({med_ours*1000:.0f} ms vs {med_base*1000:.0f} ms). "
            f"In **aggregate we are ×{agg:.2f} {agg_dir}** than ltlsynt. "
            f"The genuine value is the **{len(ours_win_base_to)} "
            f"{'spec' if len(ours_win_base_to) == 1 else 'specs'} ltlsynt cannot "
            f"synthesize in {args.timeout}s that we do**. The "
            f"completeness blocker is **{len(less_complete)} specs ltlsynt solves that we don't** — now "
            f"dominated by **{len(false_unreal)} false-UNREALs** from output-free assumption clusters, "
            f"not parse bugs.\n")
    L.append(SENTINEL_END + "\n")
    section = "".join(L)

    # Inject as a self-delimited section: replace between the sentinels if they
    # already exist (so reruns only touch this section), else append to the doc.
    existing = ""
    if os.path.exists(args.out):
        with open(args.out) as f:
            existing = f.read()
    if SENTINEL_START in existing and SENTINEL_END in existing:
        pre = existing[:existing.index(SENTINEL_START)]
        post = existing[existing.index(SENTINEL_END) + len(SENTINEL_END):]
        new = pre + section.rstrip("\n") + post
    elif existing.strip():
        new = existing.rstrip("\n") + "\n\n" + section
    else:
        new = "# BENCHGRAPH\n\n" + section
    with open(args.out, "w") as f:
        f.write(new)


if __name__ == "__main__":
    main()
