#!/usr/bin/env python3
"""Model-check an AIGER controller against an LTL formula.

The check is language inclusion: every trace generated by the AIGER circuit must
satisfy the formula.  Internally this builds the controller transition system
with Spot's AIGER reader and checks emptiness of controller & !formula.
"""

import argparse
import subprocess
import sys


def read_formula(args):
    if args.formula is not None:
        return args.formula
    if args.formula_file is not None:
        with open(args.formula_file, encoding="utf-8") as fp:
            return fp.read().strip()
    if args.tlsf is not None:
        # Use the case-preserving `ltl` dialect: the AIGER controller keeps the
        # spec's original signal names, but `ltlxba` lowercases atoms (for
        # ltlsynt), which would not match the controller's symbols.
        proc = subprocess.run(
            [args.tlsf2ltl, "--format", "ltl", args.tlsf],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if proc.returncode != 0:
            sys.stderr.write(proc.stderr)
            raise SystemExit(proc.returncode)
        return proc.stdout.strip()
    raise SystemExit("one of --formula, --formula-file, or --tlsf is required")


def read_aiger(args):
    if args.aiger is not None:
        with open(args.aiger, encoding="utf-8") as fp:
            return fp.read()
    if args.tlsf is None:
        raise SystemExit("--compose requires --tlsf")
    cmd = [args.compose, "--aiger"]
    if args.split:
        cmd.append("--split")
    if args.abssynthe is not None:
        cmd.extend(["--abssynthe", args.abssynthe])
    if args.ltlsynt is not None:
        cmd.extend(["--ltlsynt", args.ltlsynt])
    cmd.append(args.tlsf)
    proc = subprocess.run(
        cmd,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(proc.returncode)
    return proc.stdout


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Verify an AIGER controller against an LTL formula."
    )
    parser.add_argument("--aiger", help="read AIGER from FILE")
    parser.add_argument("--compose", default="tlsfcompose",
                        help="tlsfcompose path used when --aiger is omitted")
    parser.add_argument("--abssynthe", help="AbsSynthe path for tlsfcompose")
    parser.add_argument("--ltlsynt",
                        help="ltlsynt path for tlsfcompose; use /bin/false to "
                             "assert no fallback is used")
    parser.add_argument("--split", action="store_true",
                        help="pass --split to tlsfcompose")
    parser.add_argument("--tlsf", help="TLSF spec to translate and/or compose")
    parser.add_argument("--tlsf2ltl", default="tlsf2ltl",
                        help="tlsf2ltl path used with --tlsf")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--formula", help="LTL formula string")
    group.add_argument("--formula-file", help="read LTL formula from FILE")
    parser.add_argument("--show-counterexample", action="store_true",
                        help="print an accepting word when verification fails")
    return parser.parse_args(argv)


def main(argv):
    args = parse_args(argv)
    try:
        import spot
    except ImportError as exc:
        raise SystemExit(f"Spot Python bindings are required: {exc}") from exc

    formula_text = read_formula(args)
    aiger_text = read_aiger(args)

    formula = spot.formula(formula_text)
    circuit = spot.aiger_circuit(aiger_text, bdd_dict=spot._bdd_dict)
    circuit_aps = set(circuit.input_names()) | set(circuit.output_names())
    formula_aps = {str(ap) for ap in spot.atomic_prop_collect(formula)}
    missing = sorted(formula_aps - circuit_aps)
    if missing:
        sys.stderr.write(
            "verify-aiger-ltl: formula APs missing from AIGER symbols: " +
            ",".join(missing) + "\n"
        )
        return 2

    system = circuit.as_automaton()
    bad = spot.translate(spot.formula.Not(formula))
    product = spot.product(system, bad)
    if product.is_empty():
        print("verified")
        return 0

    sys.stderr.write("verify-aiger-ltl: controller violates formula\n")
    if args.show_counterexample:
        word = product.accepting_word()
        sys.stderr.write(str(word) + "\n")
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
